# Generated by Django 6.0.4 on 2026-04-18 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('title', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='pricelisting',
            unique_together={('game', 'store', 'format_type')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'game')},
        ),
    ]
