# Generated by Django 6.0.4 on 2026-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_store_name_alter_game_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='recorded_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricelisting',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
