

services:
  web:
    build: .
    container_name: dealtracker_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Esto sincroniza tu código local con el contenedor
    ports:
      - "8000:8000"
    env_file:
      - .env  # 12-factor: Carga variables de entorno desde un archivo .env